import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/sessionWrapper";
import Header from "@/components/header";

import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { ReactQueryProviders } from "@/feature/reactQueryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Projet HBI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProviders>
      <SessionWrapper>
        <html lang="en">
          <body className={inter.className}>
            <div className="flex flex-col w-full h-full min-h-screen  ">
              <Header />
              <main className="flex flex-col">
                <EdgeStoreProvider>{children}</EdgeStoreProvider>
              </main>
            </div>
            <Toaster />
          </body>
        </html>
        {/* {process.env.NODE_ENV === "development" && <ReactQueryDevtools />} */}
      </SessionWrapper>
    </ReactQueryProviders>
  );
}
