import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/sessionWrapper";
import Header from "@/components/header";

import { Toaster } from "@/components/ui/sonner";

import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Projet HBI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col w-full h-full min-h-screen  ">
            <Header />
            <main
              className="flex flex-col  
            "
            >
              {/* items-center justify-center w-[75%] h-auto max-w-3xl px-4 py-4 mx-auto sm:px-6 md:py-6 */}
              <EdgeStoreProvider>{children}</EdgeStoreProvider>
            </main>
          </div>
          <Toaster />
        </body>
      </html>
    </SessionWrapper>
  );
}
